### ISSUE TITLE
Cannot get port state of a component that is not connected to a subnet.

### ISSUE THREAD

**Issue by NogginBops** [inda19plusplus/logik#48]
Currently the application panics when trying to get the port state of a component that is not connected to any subnet.

It would make the code a lot cleaner if it returned floating in this case instead.

While fixing this it might also be worth looking at having the component port states be independent to the subnet so it's easier to diagnose where conflicts arise. But this is only a minor concern.

**Comment by Rickard-Martensson** [comment]
Ill fixy fixy
