### ISSUE TITLE
Gates

### ISSUE THREAD

**Issue by weerox** [inda19plusplus/logik#6]
Properties required for gates:

- Direction: north, east, south, west
- Position: x, y
- Pin Placement: ?

**Comment by weerox** [comment]
The gate should probably also have a Type property which defines whether it is an AND, OR, XOR etc.

**Comment by NogginBops** [comment]
Closing this as there is a working representation of gates.
Currently gates are represented in the front-end with:
```
ID: An ID to identify the component instance between the backend and frontend.
Type: The type of the component e.g And, Not, etc.
Position: The position of the origin of the component.
Orientation: The orientation of the component.
```
We can open an issue if we want to change anything regarding this.
